# Harvests a device identity profile from a real Android device over adb
# and writes device_profile.ini for genshinimpact_nx.
#
# Usage:
#   1. Enable USB debugging on the device that already plays the supported
#      Genshin Impact client and connect it.
#   2. powershell -ExecutionPolicy Bypass -File tools\harvest_device_profile.ps1
#   3. Copy the generated device_profile.ini to the SD card:
#      sdmc:/config/genshinimpact_nx/device_profile.ini
#
# Notes:
#   - ANDROID_ID is app-scoped on modern Android; `settings get secure
#     android_id` returns the system value, not the one the game sees, so
#     it is emitted commented out.  Only enable it if you know the app
#     scoped value.
#   - device_fp is a session token produced by the miHoYo SDK fingerprint
#     flow and cannot be read from system properties; leave it unset unless
#     you captured one from a real client session.

$ErrorActionPreference = 'Stop'

if (-not (Get-Command adb -ErrorAction SilentlyContinue)) {
    Write-Error "adb not found in PATH. Install platform-tools first."
}

function Get-Prop([string]$name) {
    (adb shell getprop $name).Trim()
}

$props = [ordered]@{
    model           = 'ro.product.model'
    manufacturer    = 'ro.product.manufacturer'
    brand           = 'ro.product.brand'
    product         = 'ro.product.name'
    device          = 'ro.product.device'
    board           = 'ro.product.board'
    hardware        = 'ro.hardware'
    platform        = 'ro.board.platform'
    fingerprint     = 'ro.build.fingerprint'
    version_release = 'ro.build.version.release'
    version_sdk     = 'ro.build.version.sdk'
    security_patch  = 'ro.build.version.security_patch'
    incremental     = 'ro.build.version.incremental'
}

$lines = @(
    '# device_profile.ini for genshinimpact_nx',
    '# Generated by tools/harvest_device_profile.ps1',
    ''
)

foreach ($entry in $props.GetEnumerator()) {
    $value = Get-Prop $entry.Value
    if ($value) {
        $lines += "$($entry.Key)=$value"
    } else {
        $lines += "# $($entry.Key)= (device returned empty)"
    }
}

$androidId = (adb shell settings get secure android_id).Trim()
$lines += ''
$lines += '# App-scoped on modern Android; enable only if you know the value:'
if ($androidId -and $androidId -ne 'null') {
    $lines += "# android_id=$androidId"
} else {
    $lines += '# android_id='
}
$lines += '# Session token from the SDK fingerprint flow, if captured:'
$lines += '# device_fp='

$outPath = Join-Path $PSScriptRoot 'device_profile.ini'
$lines | Set-Content -Encoding ascii -Path $outPath
Write-Host "Wrote $outPath"
Write-Host "Copy it to: sdmc:/config/genshinimpact_nx/device_profile.ini"
