# Harvests a device identity profile from a real Android device over adb
# and writes device_profile.ini for genshinimpact_nx.
#
# Usage:
#   1. Enable USB debugging on the device that already plays the supported
#      Genshin Impact client and connect it.
#   2. powershell -ExecutionPolicy Bypass -File tools\harvest_device_profile.ps1
#   3. Copy the generated device_profile.ini to the SD card:
#      sdmc:/config/genshinimpact_nx/device_profile.ini
#
# Notes:
#   - ANDROID_ID is app-scoped on modern Android. The shell-visible settings
#     value is not collected because it is not the value the game sees.
#   - device_fp is a session token produced by the miHoYo SDK fingerprint
#     flow and cannot be read from system properties; leave it unset unless
#     you captured one from a real client session.

$ErrorActionPreference = 'Stop'

if (-not (Get-Command adb -ErrorAction SilentlyContinue)) {
    Write-Error "adb not found in PATH. Install platform-tools first."
}

function Invoke-Adb([string[]]$Arguments) {
    $output = & adb @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "adb $($Arguments -join ' ') failed with exit code $LASTEXITCODE"
    }
    ($output -join "`n").Trim()
}

function Get-Prop([string]$name) {
    Invoke-Adb @('shell', 'getprop', $name)
}

$devices = @(Invoke-Adb @('devices') -split "`n" |
    Where-Object { $_ -match "`tdevice$" })
if ($devices.Count -ne 1) {
    throw "Expected exactly one authorized adb device, found $($devices.Count)."
}

$props = [ordered]@{
    model           = 'ro.product.model'
    device_name     = 'ro.product.marketname'
    manufacturer    = 'ro.product.manufacturer'
    brand           = 'ro.product.brand'
    product         = 'ro.product.name'
    device          = 'ro.product.device'
    board           = 'ro.product.board'
    hardware        = 'ro.hardware'
    platform        = 'ro.board.platform'
    fingerprint     = 'ro.build.fingerprint'
    build_id        = 'ro.build.id'
    display_id      = 'ro.build.display.id'
    build_host      = 'ro.build.host'
    build_user      = 'ro.build.user'
    characteristics = 'ro.build.characteristics'
    version_release = 'ro.build.version.release'
    version_sdk     = 'ro.build.version.sdk'
    security_patch  = 'ro.build.version.security_patch'
    incremental     = 'ro.build.version.incremental'
}

$values = [ordered]@{}
foreach ($entry in $props.GetEnumerator()) {
    $values[$entry.Key] = Get-Prop $entry.Value
}
if (-not $values.device_name) {
    $values.device_name = $values.model
}

$lines = @(
    '# device_profile.ini for genshinimpact_nx',
    '# Generated by tools/harvest_device_profile.ps1',
    ''
)

foreach ($entry in $values.GetEnumerator()) {
    $value = $entry.Value
    if ($value) {
        $lines += "$($entry.Key)=$value"
    } else {
        $lines += "# $($entry.Key)= (device returned empty)"
    }
}

$lines += ''
$lines += '# App-scoped on modern Android; enable only if independently known:'
$lines += '# android_id='
$lines += '# Session token from the SDK fingerprint flow, if captured:'
$lines += '# device_fp='

$outPath = Join-Path $PSScriptRoot 'device_profile.ini'
$lines | Set-Content -Encoding utf8 -Path $outPath
Write-Host "Wrote $outPath"
Write-Host "Copy it to: sdmc:/config/genshinimpact_nx/device_profile.ini"
